---
title: "Strategy Unit Data Science Coffee Disaster Counter ☕ 💥"
format:
  dashboard:
    orientation: columns
    nav-buttons:
       - icon: github
         href: https://github.com/The-Strategy-Unit/coffee-disaster
---

# Tracker

## Column {width=60%}

```{r}
coffee_disasters <- read.csv("coffee-disaster-tracking.csv")
last_disaster_date <- max(as.Date(coffee_disasters$Date))

days_since <- as.numeric(difftime(Sys.Date(), last_disaster_date, units = "days"))
```

```{r}
  bslib::value_box(
    title = "Days since last disaster",
    value = days_since,
    showcase = bsicons::bs_icon("cup-hot-fill"),
    max_height = 300,
    htmltools::p(glue::glue("Last disaster: {format(last_disaster_date, '%B %d, %Y')}"))
  )
```

## Column {width=40%}

When a coffee disaster occurs, update the `coffee-disaster-tracking.csv` file with the disaster date in YYYY-MM-DD format and your GitHub username on the bottom row. 

The counter will automatically update on the next scheduled refresh.

# Statistics

```{r}
ggplot2::ggplot(coffee_disasters) +
  ggplot2::geom_bar(
    ggplot2::aes(
      y = Person,
      fill = Person
    ),
    stat = "count"
  ) +
  ggplot2::scale_x_continuous(
    breaks = seq(
      0,
      ceiling(max(table(coffee_disasters$Person))),
      by = 1
    )
  ) +
  ggplot2::xlab("Count") +
  ggplot2::ggtitle("Coffee disasters per person") +
  NHSRtheme::theme_nhs()

```
